name: VCorePaper
version: ${project.version}
main: de.verdox.vcorepaper.VCorePaper
api-version: 1.16
authors: [ Verdox ]
softdepend:
  - HolographicDisplays

commands:
  debug:
    description: "Main Debug Command for VCorePaper"
    permission: "VCore.debug"
