name: VCorePaper
version: ${project.version}
main: de.verdox.vcorepaper.VCorePaper
api-version: 1.16
authors: [ Verdox ]
softdepend:
  - HolographicDisplays
  - ProtocolLib
  - PlaceholderAPI

commands:
  debug:
    description: "Main Debug Command for VCorePaper"
    permission: "VCore.debug"
  nms:
    description: "Main Debug for NMS Testing"
    permission: "VCore.nms"
  playerhandler:
    description: "Admin Command for PlayerHandler"
    permission: "vcore.playerhandler"
  playerapi:
    description: "Admin Command for PlayerAPI"
    permission: "vcore.playerapi"
  talkingNPC:
    description: "Talking NPC"
    permission: "vcore.talkingNPC"