name: VCorePaperWorkerNPCModule
version: ${project.version}
main: de.verdox.vcore.workernpc.VCoreWorkerNPCModule
api-version: 1.16
authors: [ Verdox ]
depend: [VCorePaper, VCorePaperGUIModule, VCorePaperNBTModule, VCorePaperEventModule, VCorePaperNMSModule]
commands:
  workingNPC:
    description: "Working NPC Admin Command"
    permission: "vcore.workingNPC"