name: VCoreGUIModule
version: ${project.version}
main: de.verdox.vcorepaper.VCoreGUIModule
api-version: 1.16
authors: [ Verdox ]
depend:
  - VCorePaper
  - VCorePaperEventModule
  - VCorePaperNBTModule